### ISSUE TITLE
As a NOI facility manager I want to access to the detail view of a display by scanning a QR code in order to easily find the right display.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.epaper.webapp#33]
It is important that in case the scanned display isn't already present in the system, the user should be notified and asked if he wants to add it to the system.

If yes, the application should start the procedure to add a new display with the information about the display provided through the QR code (eg. ID)  already filled.

MVP1:
- [x] At QR code is on the display and generated outside of the webapp with a 3rd-party-tool. The webapp just provides a link into the configuration page, which needs to be encoded inside the given QR code

MVP2:
- [x] #79

**Comment by SaimonasFOS** [comment]
@sseppi @Piiit 

The QR code link should be as follows:

https://epaper.opendatahub.testingmachine.eu/displays?displayId=<...>&screenWidth=<...>&screenHeight=<...>&screenBitDepth=<...>

For example: https://epaper.opendatahub.testingmachine.eu/displays?displayId=a988aaae-42f7-4f6c-8cf8-01a3870083e7&screenWidth=1872&screenHeight=1404&screenBitDepth=4

Width, height and bit depth parameters are not mandatory, but they can be useful for inserting a new display.
Otherwise, the link can just be https://epaper.opendatahub.testingmachine.eu/displays?displayId=<...>

You can test it after merging this PR: https://github.com/noi-techpark/it.bz.opendatahub.epaper.webapp/pull/80

**Comment by Piiit** [comment]
@SaimonasFOS @sseppi Works
