### ISSUE TITLE
As a tool user I want a Template list view to have a quick overview of the actual existing template.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.epaper.webapp#42]
For each template the view must show at least:
- name;
- description.

Options should be:
- [x] an edit button
- [x] a delete button
- [x] a create button

**UPDATE**
Some problems exist:

- [x] We can have duplicate names currently, which is not correct... Names should be unique
- [x] Clicking on "Show Content" shows "Cannot load preview" sometimes 
![image](https://user-images.githubusercontent.com/6096063/151001406-3ca625b4-9ca9-46a5-8e1c-6da33adb9454.png)

**UPDATE 2**
The following is still not working:
- [ ] Delete gives "Failed to delete image" (tested with "Free SL")

I tested it again and it always happens, when a template is associated to a display. So you would need to delete the display first, and then you can delete the template. But that is not what we want... we need to fix this.

**Comment by Piiit** [comment]
@SaimonasFOS @giovannigiannotta See UPDATE section in main comment

**Comment by SaimonasFOS** [comment]
@Piiit 
> We can have duplicate names currently, which is not correct... Names should be unique

Yes, will fix it in the future

> Clicking on "Show Content" shows "Cannot load preview" sometimes

That is intentional, happens when the template has no background picture.

> Delete gives "Failed to delete image" (tested with "Free SL")

Just checked that, happens when a Template is assigned to a Display, didn't catch this case in my testing. Will fix this soon.

**Comment by Piiit** [comment]
@SaimonasFOS Please see Update2 above

**Comment by SaimonasFOS** [comment]
@Piiit That's actually because the old template system would assign a template to a display. So there's a display that still has a template related to it in your database. 
Current template system doesn't do that, it just copies background image and field information to a display based on a template. I just tested it to be sure and even after applying a new template to a display I was able to delete that template.
In the future if we decide to change display content when changing the template, this relation will be needed again, so I left it there. But with the current workflow there should be no problem if you fix the database (I cannot do it since I do not see which display has that template assigned)

**Comment by Piiit** [comment]
@SaimonasFOS I deleted the Free SL template and related display... 

@sseppi Is it ok to delete the whole DB and refill?

**Comment by Piiit** [comment]
I close this issue in the meantime, lets open a new one if errors come up again during MVP2

**Comment by sseppi** [comment]
> @sseppi Is it ok to delete the whole DB and refill?

I think tha we can clean everything and restart, or delete everything but the two real Totems

**Comment by Piiit** [comment]
I deleted some things with the GUI, everything seems to work as expected... so I did not touch the DB for the moment... let me know if a strange error occurs again, so I can purge the DB
