### ISSUE TITLE
As NOI secretary, I want to plan updates of room information on each e-display beforehand, where some automated system triggers the update on time

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.epaper.webapp#52]
In the scheduler inside the detail view of a display the user has the possibility to:
- [x] see the scheduled content that will be sent to the display including:
  - [x] timing
  - [x] preview of the content
- [x] plan a new content 

Each content to be shown on the display should have:
- [x] an image
- [x] a start time (date and time)
- [x] an end time (date and time)

In case that there is no content to show on a display the system will show a default content that can be either:
- [x] upcoming events in case of Seminarroom or Meeting Rooms
> at the moment we can show only one content, not different templates for the same content per point in time

Postponed to MVP2:
- [x] #77
- [x] #78

**Comment by SaimonasFOS** [comment]
https://github.com/noi-techpark/it.bz.opendatahub.epaper.api/pull/29
https://github.com/noi-techpark/it.bz.opendatahub.epaper.webapp/pull/59

For "automated system triggers the update on time" part of this task maybe a different approach is needed. The current implementation of the cron method that updates displays doesn't quite fit the new event system that I made. But instead of redoing the cron method code, I think it would be easier to just return correct display content when a display sends a request. We can discuss this during the next sprint meeting.

**Comment by Piiit** [comment]
@SaimonasFOS I do not understand where to find the content of this user story... I move it back to TO DO
