### ISSUE TITLE
As an user of the webapp or API I want to login to the system with my Open Data Hub credentials, that is, via our Keycloak server

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.epaper.webapp#54]
This needs to be implementd for the API and the Webapp... using our Keycloak server

See https://github.com/noi-techpark/authentication-server-examples for some information

**Comment by SaimonasFOS** [comment]
https://github.com/noi-techpark/it.bz.opendatahub.epaper.api/pull/38
https://github.com/noi-techpark/it.bz.opendatahub.epaper.webapp/pull/71

for now on the API side I'm only protecting /location and /resolution, because other routes have image GET requests and HTML img component does not support authorization headers. For proper API protection, the webapp image displaying strategy needs to be different. And of course we need to figure out authentication for Displays themselves

**Comment by Piiit** [comment]
@SaimonasFOS @sseppi Works thanks
